name: 自动清空Action日志
on:
  workflow_dispatch:
jobs:
  clean_all:
    runs-on: ubuntu-latest
    steps:
      - name: 删除【港澳台更新】历史记录
        uses: bervProject/delete-workflow-runs@main
        with:
          repository: ${{ github.repository }}
          workflow: "港澳台更新"
          keep: 0

      - name: 删除【json用】历史记录
        uses: bervProject/delete-workflow-runs@main
        with:
          repository: ${{ github.repository }}
          workflow: "json用"
          keep: 0

